[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true


# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Duration (in seconds) of the user session expiry
user_session_timeout = 1296000  # 15 days

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

[features]
# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = true

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = true

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = true
    # Define accepted file types using MIME types
    # Examples:
    # 1. For specific file types:
    #    accept = ["image/jpeg", "image/png", "application/pdf"]
    # 2. For all files of certain type:
    #    accept = ["image/*", "audio/*", "video/*"]
    # 3. For specific file extensions:
    #    accept = { "application/octet-stream" = [".xyz", ".pdb"] }
    # Note: Using "*/*" is not recommended as it may cause browser warnings
    accept = ["image/jpeg", "image/png"]
    max_files = 1
    max_size_mb = 500

[features.audio]
    # Sample rate of the audio
    sample_rate = 24000

[UI]
# Name of the assistant.
name = "Wetrocloud"
custom_js = '/public/script.js'
custom_css = '/public/style.css'

# default_theme = "light"

layout = "wide"

# Description of the assistant. This is used for HTML tags.
# description = "Wetrocloud: AI + Your Resources"

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
#[UI]
# ...
# This can either be a css file in your `public` dir or a URL


# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file can be served from the public directory.
#[UI]
# ...
# This can either be a css file in your `public` dir or a URL



# Specify a custom meta image url.
custom_meta_image_url = "/public/favicon.svg"

# Specify a custom build directory for the frontend.
# This can be used to customize the frontend code.
# Be careful: If this is a relative path, it should not start with a slash.
# custom_build = "./public/build"

# Specify optional one or more custom links in the header.
# [[UI.header_links]]
#     name = "Issues"
#     icon_url = "https://avatars.githubusercontent.com/u/128686189?s=200&v=4"
#     url = "https://github.com/Chainlit/chainlit/issues"

[meta]
generated_by = "2.2.1"

[UI.theme]
  default = "light"  # Set the default theme to light or dark

  [UI.theme.light]
    background = "#FFFFFF"  # Background color
    paper = "#F0F0F0"       # Paper elements color

    [UI.theme.light.primary]
      main = "#3498db"      # Primary color
      dark = "#2980b9"      # Darker shade of primary color
      light = "#5dade2"     # Lighter shade of primary color

  [UI.theme.dark]
    background = "#2C3E50"
    paper = "#34495E"

    [UI.theme.dark.primary]
      main = "#e74c3c"
      dark = "#c0392b"
      light = "#f1948a"